apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnloop-react-backend
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    matchLabels:
      app: learnloop-react-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: learnloop-react-backend
    spec:
      containers:
        - name: learnloop-react-backend
          image: "{{ .Values.image }}/react_backend:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
          - name: REACT_APP_BACKEND_BASE_URL
            value: "{{ .Values.env.backendBaseUrl }}"
          - name: AZURE_OPENAI_ENDPOINT
            value: "{{ .Values.azureOpenaiEndpoint }}"
          envFrom:
            - secretRef:
                name: learnloop-secret
          {{- if .Values.azure }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/etc/secrets"
              readOnly: true
          {{- end }}
      {{- if .Values.azure }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "learnloop-secretproviderclass"
      {{- end }}
