apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnloop-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "1500m" # 1.5GB max upload size
    # Sticky session annotations
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "learnloop-session"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"  # 24 hours
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnloop-student
                port:
                  number: 80
          - path: /surf
            pathType: Prefix
            backend:
              service:
                name: learnloop-auth
                port:
                  number: 80
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: learnloop-auth
                port:
                  number: 80