apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learnloop-ingress
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
spec:
  tls:
    - hosts:
        - "{{ .Values.hostname }}"
  rules:
    - host: "{{ .Values.hostname }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learnloop-auth
                port:
                  number: 80
          - path: /student
            pathType: Prefix
            backend:
              service:
                name: learnloop-student
                port:
                  number: 80
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: learnloop-react-frontend
                port:
                  number: 80
          - path: /react-backend
            pathType: Prefix
            backend:
              service:
                name: learnloop-react-backend
                port:
                  number: 80