apiVersion: v1
kind: Service
metadata:
  name: learnloop-react-frontend
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: learnloop-react-frontend
