name: build and push container

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set lowercase repository name
        id: repo_name
        run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: List files in the directory
        run: ls -la
        working-directory: ./auth_app

      - name: Build and push Student Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./student_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/student_app:main
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Auth Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./auth_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/auth_app:main
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Teacher Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./teacher_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/teacher_app:main
          labels: ${{ steps.meta.outputs.labels }}
