name: build and push container

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set lowercase repository name
        id: repo_name
        run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Auth Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./auth_app
          file: ./auth_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/auth_app:main
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Student Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./student_app
          file: ./student_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/student_app:main
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push React Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./react_app/backend
          file: ./react_app/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/react_backend:main
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push React Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./react_app
          file: ./react_app/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME_LOWER }}/react_frontend:main
          labels: ${{ steps.meta.outputs.labels }}
